def GetTwoStoryCombos():
	twoStories = [['inheritance', 'pharmacy', 'A orders drugs. B asks for prescription. A produces prescription. A takes receipt.  A leaves. A attends funeral. '], 
	['fantasy', 'tourBus', 'Monster holds B captive. A slays monster. A rescues B. A departs with B. A and B get married. A and B visit a Landmark. '], 
	['tourBus', 'fantasy', 'A arrives at Boarding Location. A tells B to board bus. B boards bus. B falls in love with A. A departs with B. A and B kiss. A and B get married. A and B live happily ever after. '], 
	['catLover', 'cattleDriver', 'A begins the day. A injures arm. A bandages arm. A walks to river. A rides horse. A hits the ground. A rescues cow. A sees frightened cat at river. A puts on gloves. A returns with cow. '], 
	['stagecoach', 'robbery', 'A arrives with Stagecoach. A waits. B enters Stagecoach. B tells A to go to the White House. A departs with B. A converses with B. A informs B of arrival. Police arrest A. '], 
	['tourBus', 'robbery', 'A demands money. B presses alarm. B collects money. A tells B to board bus. Police arrive. B gives A money. Police arrest A. '], 
	['inheritance', 'movie', "A drives to B's house. A learns about uncle. A attends funeral. A meets B. A drives to theater. A parks car. A refuses inheritance. "], 
	['stagecoach', 'tourBus', 'A arrives with Stagecoach. A waits. B enters Stagecoach. B tells A to go to the White House. A and B visit a Landmark. A asks B whats next. A converses with B. A departs with B. A and B arrive at Boarding Location. '], 
	['fantasy', 'catLover', 'Monster holds B captive. A slays monster. A arrives home with cat. A sneezes. '], 
	['stagecoach', 'robbery', 'A arrives with Stagecoach. A approaches B. A pulls out gun. B greets A. B is scared. A departs with B. A demands money. B collects money. B gives A money. A drives away. '], 
	['movie', 'catLover', 'A slips. A hits the ground. A meets B. A drives to theater. A sneezes. '], 
	['robbery', 'anchorhead', 'A gives B flask. A discovers safe. A talks to B. A waits in line. A covers face. A approaches B. A sees B. A pulls out gun. A demands money. A meets B. B collects money. B is scared. B gives A money. A gives B amulet. B tells A about sewer. Police arrive. A discovers book in sewer. '], 
	['robbery', 'anchorhead', 'A enters bank. A discovers safe. B greets A. A approaches B. B is scared. A discovers book in sewer. '], 
	['tourBus', 'pharmacy', 'A arrives at Boarding Location. A orders drugs. B asks for prescription. A produces prescription. B checks prescription. B delivers drugs. A swipes a card. A takes receipt. B boards bus. A leaves. '], 
	['anchorhead', 'catLover', 'A leaves house. A arrives home with cat. A learns safe combo. A finds magic shop. A meets B. A gets flask. A opens safe. A finds secret observatory. A sneezes. '], 
	['robbery', 'anchorhead', 'A enters bank. A scans bank. B tells A about sewer. A discovers book in sewer. '], 
	['stagecoach', 'inheritance', 'A learns about uncle. A arrives with Stagecoach. B enters Stagecoach. A meets B. A goes to bar. A departs with B. A refuses inheritance. '], 
	['fantasy', 'pharmacy', 'B delivers drugs. A swipes a card. A takes receipt. A slays monster. A rescues B. B falls in love with A. A leaves. '], 
	['fantasy', 'robbery', 'B presses alarm. A demands money. Police arrive. A rescues B. A and B kiss. B collects money. A covers face. Police arrest A. '], 
	['catLover', 'stagecoach', 'A begins the day. A waits. A walks to river. A arrives with Stagecoach. B enters Stagecoach. A puts on gloves. B tells A to go to the White House. A converses with B. A departs with B. A informs B of arrival. A and B arrive at White House. '], 
	['fantasy', 'robbery', 'B greets A. A covers face. A approaches B. B is scared. A pulls out gun.  A slays monster. B presses alarm. Police arrive. Police arrest A. '], 
	['anchorhead', 'fantasy', 'A leaves house. A gets flask. A learns safe combo. A slays monster. A meets B. B falls in love with A. A gets crypt key. A find coffin. A rescues B. A finds magic shop. A gets amulet. A and B kiss. A discovers safe. A and B get married. A and B live happily ever after. '], 
	['robbery', 'inheritance', 'A enters bank. A meets B. A waits in line. A sees B. A scans bank. A refuses inheritance. '], 
	['tourBus', 'fantasy', 'A arrives at Boarding Location. A and B kiss. B boards bus. A welcomes B. A departs with B. A and B visit a Landmark. A and B get married. A and B live happily ever after. '], 
	['robbery', 'cattleDriver', 'A enters bank. A returns with cow. '], 
	['inheritance', 'robbery', 'A goes to bar. A learns about uncle. A gets partial inheritance. A attends funeral. A meets B. A enters bank. A collects inheritance. '], 
	['robbery', 'tourBus', 'A enters bank. B greets A. A departs with B. A and B visit a Landmark. A asks B whats next. A and B arrive at Boarding Location. '], 
	['inheritance', 'movie', 'A gets partial inheritance. A learns about uncle. B says goodbye to A. '], 
	['anchorhead', 'inheritance', 'A leaves house. A finds secret observatory. A finds magic shop. A discovers safe. A gets crypt key. A learns safe combo. A opens safe. A attends funeral. A meets B. A refuses inheritance. '], 
	['tourBus', 'robbery', 'A approaches B. B is scared. A pulls out gun. A demands money. B presses alarm. Police arrive. B collects money. B gives A money. A covers face. A leaves bank. A gets in car. A sees B. B greets A. B boards bus. A drives away. '], 
	['fantasy', 'tourBus', 'Monster holds B captive. A slays monster. A rescues B. A departs with B. A and B visit a Landmark. B falls in love with A. '], 
	['fantasy', 'cattleDriver', 'Monster holds B captive. A smacks saddle. A slips. A hits the ground. A arrives at river. A and B kiss. B falls in love with A. A finds a frightened cow. A injures arm. A bandages arm. A and B get married. A rescues cow. A and B live happily ever after. '], 
	['anchorhead', 'cattleDriver', 'A slips. A smacks saddle. A arrives at river. A learns safe combo. A finds a frightened cow. A rescues cow. A meets B. A gets crypt key. A rides horse. A bandages arm. A talks to B. A finds secret observatory. A gets skull. A hits the ground. A gets amulet. A injures arm. A gives B amulet. A opens safe. A returns with cow. '], 
	['tourBus', 'fantasy', 'A arrives at Boarding Location. A tells B to board bus. B boards bus. A welcomes B. A and B live happily ever after. '], 
	['robbery', 'cattleDriver', 'A approaches B. A covers face. A pulls out gun. A enters bank. A finds a frightened cow. B is scared. A hits the ground. A injures arm. A rescues cow. A returns with cow. '], 
	['robbery', 'inheritance', 'A approaches B. A refuses inheritance. '], 
	['catLover', 'movie', 'A begins the day. A feeds cats. A walks to river. A slips. A hits the ground. A sees frightened cat at river. A puts on gloves. A injures arm. A meets B. A rescues cat. Cat injures A. A parks car. A arrives home with cat. A sneezes. '], 
	['inheritance', 'cattleDriver', 'A learns about uncle. A gets partial inheritance. A begins the day. A rides horse. A hits the ground. A collects inheritance. '], 
	['anchorhead', 'pharmacy', "A finds magic shop. A gets flask. A leaves. "], 
	['stagecoach', 'robbery', 'A arrives with Stagecoach. A waits. B enters Stagecoach. B tells A to go to the White House. A pulls out gun. A converses with B. A demands money. B presses alarm. Police arrive. Police arrest A. '], 
	['robbery', 'movie', 'A buys tickets. A and B buy popcorn. A and B buy drinks. A and B enter the theater. A and B sit down. Movie begins. A uses the bathroom. A and B talk. A approaches B. A and B hold hands. A pulls out gun. A demands money. B says goodbye to A. '], 
	['robbery', 'stagecoach', 'A sees B. A converses with B. A covers face. B is scared. A pulls out gun. A scans bank. A demands money. A departs with B. Police arrive. Police arrest A. '], 
	['cattleDriver', 'pharmacy', 'A begins the day. A smacks saddle. A arrives at river. A rescues cow. A takes receipt. A leaves. '], 
	['inheritance', 'cattleDriver', 'A begins the day. A goes to bar. A rides horse. A smacks saddle. A arrives at river. A learns about uncle. A slips. A hits the ground. A finds a frightened cow. A rescues cow. A returns with cow. '], 
	['movie', 'catLover', "A drives to B's house. A meets B. A feeds cats. A walks to river. A sees frightened cat at river. A puts on gloves. A rescues cat. Cat injures A. A bandages arm. A arrives home with cat. A sneezes. "], 
	['catLover', 'cattleDriver', 'A begins the day. A feeds cats. A walks to river. A rescues cow. A returns with cow. '], 
	['stagecoach', 'inheritance', 'A arrives with Stagecoach. A waits. B enters Stagecoach. A meets B. A attends funeral. '], 
	['movie', 'fantasy', 'A rescues B. A meets B. A drives to theater. A and B kiss. A buys tickets. A and B buy popcorn. A and B live happily ever after. '], 
	['robbery', 'anchorhead', 'A enters bank. A sees B. B greets A. A waits in line. A scans bank. A approaches B. A shows B skull. A covers face. B is scared. A demands money. B presses alarm. Police arrive. B collects money. B gives A money. A leaves bank. A learns safe combo. A drives away. '], 
	['tourBus', 'robbery', 'A approaches B. B greets A. A covers face. B is scared. A pulls out gun. A demands money. B presses alarm. B collects money. A arrives at Boarding Location. B gives A money. A tells B to board bus. B boards bus. A welcomes B. Police arrive. A gets in car. A drives away. '], 
	['stagecoach', 'fantasy', 'A arrives with Stagecoach. A and B get married. A and B live happily ever after. '], 
	['cattleDriver', 'pharmacy', 'A begins the day. A rides horse. A smacks saddle. A orders drugs. A leaves. '], 
	['robbery', 'cattleDriver', 'A enters bank. A scans bank. A waits in line. A approaches B. B greets A. B is scared. A pulls out gun. A covers face. A demands money. B presses alarm. A rides horse. Police arrive. A smacks saddle. Police arrest A. '], 
	['catLover', 'anchorhead', 'A begins the day. A feeds cats. A slips. A walks to river. A discovers safe. A learns safe combo. A opens safe. A puts on gloves. A injures arm. A bandages arm. A rescues cat. Cat injures A. A arrives home with cat. A sneezes. '], 
	['inheritance', 'stagecoach', 'A departs with B. A converses with B. A gets partial inheritance. A informs B of arrival. A attends funeral. '], 
	['tourBus', 'robbery', 'A arrives at Boarding Location. A approaches B. A tells B to board bus. A pulls out gun. B is scared. A demands money. B collects money. B presses alarm. Police arrive. A covers face. Police arrest A. '], 
	['movie', 'catLover', "A drives to B's house. A hits the ground. A injures arm. A drives to theater. A parks car. A rescues cat. A and B buy popcorn and soda. Cat injures A. A and B enter the theater. A and B sit down. Movie begins. A bandages arm. A arrives home with cat. A sneezes. "], 
	['inheritance', 'tourBus', 'A gets partial inheritance. A goes to bar. A attends funeral. A learns about uncle. A meets B. A and B arrive at Boarding Location. '], 
	['anchorhead', 'tourBus', 'A leaves house. A departs with B. A and B arrive at Boarding Location. '], 
	['catLover', 'fantasy', 'A begins the day. A feeds cats. A and B get married. A and B live happily ever after. '], 
	['inheritance', 'pharmacy', 'A orders drugs. B asks for prescription. A produces prescription. B checks prescription. A learns about uncle. B delivers drugs. A pays cash. A takes change. A takes receipt. A leaves. A goes to bar. '], 
	['inheritance', 'catLover', 'A learns about uncle. A gets partial inheritance. A walks to river. A injures arm. A collects inheritance. '], 
	['cattleDriver', 'catLover', 'A begins the day. A feeds cats. A walks to river. A sees frightened cat at river. A smacks saddle. A arrives at river. A slips. A hits the ground. A slips. A injures arm. A puts on gloves. A hits the ground. A rescues cat. A bandages arm. A finds a frightened cow. A injures arm. A bandages arm. Cat injures A. A rescues cow. A arrives home with cat. A sneezes. '], 
	['stagecoach', 'pharmacy', "A arrives with Stagecoach. B refuses to sell. A waits. A leaves. "], 
	['anchorhead', 'stagecoach', 'A leaves house. A learns safe combo. B enters Stagecoach. A meets B. A finds magic shop. A gets amulet. A gets crypt key. A find coffin. A gives B amulet. A finds secret observatory. B tells A about sewer. A discovers book in sewer. '], 
	['catLover', 'robbery', 'B greets A. A covers face. A approaches B. B is scared. A pulls out gun. A demands money. B collects money. B presses alarm. A leaves bank. A gets in car. B gives A money. A drives away. A feeds cats. '], 
	['inheritance', 'stagecoach', 'A learns about uncle. A gets partial inheritance. A attends funeral. A arrives with Stagecoach. B enters Stagecoach. B tells A to go to the White House. A departs with B. A informs B of arrival. A and B arrive at White House. '], 
	['movie', 'robbery', "A drives to B's house. A approaches B. B is scared. A pulls out gun. A covers face. A demands money. A meets B. B presses alarm. Police arrive. Police arrest A. "], 
	['robbery', 'fantasy', 'A and B get married. A sees B. A approaches B. A pulls out gun. A scans bank. A covers face. A waits in line. A demands money. A and B live happily ever after. '], 
	['tourBus', 'inheritance', 'A arrives at Boarding Location. A gets partial inheritance. A attends funeral. A meets B. A goes to bar. B boards bus. A refuses inheritance. '], 
	['tourBus', 'pharmacy', 'A arrives at Boarding Location. A tells B to board bus. A leaves. '], 
	['cattleDriver', 'catLover', 'A begins the day. A rides horse. A smacks saddle. A arrives home with cat. A sneezes. '], 
	['robbery', 'cattleDriver', 'A enters bank. A finds a frightened cow. A rescues cow. A returns with cow. '], 
	['anchorhead', 'stagecoach', 'A leaves house. A gets flask. A gets crypt key. A find coffin. A gets skull. A meets B. A converses with B. A finds magic shop. A gives B flask. A gets amulet. A gives B amulet. A learns safe combo. A discovers safe. B tells A about sewer. A opens safe. A opens a puzzle box. A discovers book in sewer. '], 
	['movie', 'pharmacy', "A drives to B's house. A meets B. A drives to theater. A parks car. A orders drugs. A and B enter the theater. A and B buy drinks. A and B sit down. Movie begins. A and B enjoy the movie. A and B kiss. A leaves. "], 
	['inheritance', 'cattleDriver', 'A goes to bar. A learns about uncle. A gets partial inheritance. A attends funeral. A meets B. A returns with cow. '], 
	['cattleDriver', 'robbery', 'A begins the day. B gives A money. A gets in car. A arrives at river. A drives away. '], 
	['movie', 'tourBus', "A drives to B's house. A asks B whats next. A parks car. A tells B to board bus. B boards bus. A buys tickets. A and B buy popcorn and soda. A welcomes B. A and B visit a Landmark. A and B arrive at Boarding Location. "], 
	['inheritance', 'tourBus', 'A learns about uncle. A tells B to board bus. A gets partial inheritance. A arrives at Boarding Location. A and B visit a Landmark. A and B arrive at Boarding Location. '], 
	['anchorhead', 'robbery', 'A leaves house. A gets in car. A approaches B. B greets A. A pulls out gun. A drives away. '], 
	['robbery', 'cattleDriver', 'A hits the ground. A enters bank. A scans bank. A approaches B. B is scared. A injures arm. A bandages arm. A waits in line. B presses alarm. Police arrive. B collects money. Police arrest A. '], 
	['movie', 'fantasy', "A drives to B's house. A meets B. A drives to theater. A parks car. A buys tickets. A and B buy popcorn and soda. A and B enter the theater. A and B sit down. Movie begins. A and B enjoy the movie. A and B talk. A and B kiss. A and B live happily ever after. "], 
	['stagecoach', 'pharmacy', 'A pays cash. A waits. A takes change. B enters Stagecoach. B delivers drugs. A departs with B. A informs B of arrival. A takes receipt. A leaves. '], 
	['fantasy', 'tourBus', 'Monster holds B captive. A slays monster. A rescues B. A asks B whats next. A and B kiss. A and B get married. A and B live happily ever after. '], 
	['robbery', 'catLover', 'A approaches B. B greets A. A covers face. A enters bank. B is scared. A scans bank. A sees frightened cat at river. A leaves bank. A walks to river. A puts on gloves. A rescues cat. Cat injures A. A pulls out gun. B presses alarm. Police arrive. A gets in car. A sneezes. Police arrest A. '], 
	['cattleDriver', 'catLover', 'A begins the day. A feeds cats. A walks to river. A sees frightened cat at river. A slips. A hits the ground. A injures arm. A bandages arm. A slips. A puts on gloves. A hits the ground. A rescues cat. A arrives at river. A sneezes. '], 
	['anchorhead', 'tourBus', 'A leaves house. A gets crypt key. A departs with B. A and B visit a Landmark. A gives B flask. A finds secret observatory. A discovers safe. A asks B whats next. A talks to B. A gets skull. A learns safe combo. A and B arrive at Boarding Location. '], 
	['tourBus', 'anchorhead', 'A arrives at Boarding Location. A talks to B. B boards bus. A sees evil god. '], 
	['movie', 'pharmacy', 'A orders drugs. B asks for prescription. A meets B. A swipes a card. A pays cash. A takes receipt. A takes change. A leaves. '], 
	['catLover', 'fantasy', 'A begins the day. A feeds cats. A walks to river. A slays monster. A rescues B. A slips. A hits the ground. B falls in love with A. A and B kiss. A bandages arm. A rescues cat. A and B get married. A and B live happily ever after. '], 
	['inheritance', 'fantasy', 'A rescues B. A learns about uncle. A and B kiss. A gets partial inheritance. A attends funeral. A refuses inheritance. '], 
	['catLover', 'robbery', 'A begins the day. A feeds cats. A slips. A hits the ground. A walks to river. A gets in car. A puts on gloves. A drives away. '], 
	['stagecoach', 'fantasy', 'A arrives with Stagecoach. B enters Stagecoach. B tells A to go to the White House. A departs with B. A and B kiss. A converses with B. A and B arrive at White House. '], 
	['inheritance', 'anchorhead', 'A goes to bar. A learns about uncle. A meets B. A gets crypt key. A finds magic shop. A gets amulet. A gets flask. A finds secret observatory. A gives B flask. A find coffin. A discovers safe. A gives B amulet. A talks to B. A gets skull. B tells A about sewer. A learns safe combo. A opens safe. A discovers book in sewer. '], 
	['inheritance', 'movie', 'A drives to theater. A parks car. A buys tickets. A and B buy drinks. A meets B. A and B buy popcorn. A and B enter the theater. B says goodbye to A. A goes to bar. '],  
	['anchorhead', 'tourBus', 'A welcomes B. A departs with B. A finds magic shop. A asks B whats next. A gets crypt key. A find coffin. A discovers safe. A finds secret observatory. A learns safe combo. A tells B to board bus. A gives B flask. B boards bus. A and B arrive at Boarding Location. '], 
	['movie', 'pharmacy', "A drives to B's house. A pays cash. A leaves. "], 
	['anchorhead', 'cattleDriver', 'A leaves house. A finds secret observatory. A learns safe combo. A hits the ground. A injures arm. A discovers safe. A opens safe. A meets B. A finds magic shop. A gets amulet. A gives B amulet. A bandages arm. A opens a puzzle box. A returns with cow. '], 
	['robbery', 'anchorhead', 'A discovers safe. A opens a puzzle box. A meets B. A covers face. A waits in line. A approaches B. B is scared. A pulls out gun. A demands money. A gives B amulet. B tells A about sewer. A discovers book in sewer. '], 
	['robbery', 'tourBus', 'A tells B to board bus. A covers face. A departs with B. B is scared. B boards bus. Police arrive. Police arrest John. '], 
	['tourBus', 'catLover', 'A injures arm. A bandages arm. A tells B to board bus. B boards bus. A welcomes B. A departs with B. A and B visit a Landmark. A and B arrive at Boarding Location. '], 
	['stagecoach', 'robbery', 'A arrives with Stagecoach. A waits. B enters Stagecoach. B is scared. B greets A. A converses with B. A informs B of arrival. A and B arrive at White House. '], 
	['cattleDriver', 'catLover', 'A begins the day. A rides horse. A arrives home with cat. A sneezes. '], 
	['anchorhead', 'inheritance', 'A leaves house. A attends funeral. A goes to bar. A collects inheritance. '], 
	['robbery', 'stagecoach', 'A covers face. A approaches B. B is scared. A pulls out gun. A scans bank. A demands money. A departs with B. A informs B of arrival. A converses with B. B presses alarm. Police arrive. A and B arrive at White House. '], 
	['cattleDriver', 'catLover', 'A feeds cats. A slips. A rides horse. A smacks saddle. A slips. A hits the ground. A injures arm. A arrives at river. A walks to river. A rescues cow. A returns with cow. '], 
	['anchorhead', 'tourBus', 'A leaves house. A meets B. A learns safe combo. A finds secret observatory. A and B arrive at Boarding Location. '], 
	['robbery', 'catLover', 'A begins the day. A feeds cats. A enters bank. A waits in line. A covers face. B is scared. A walks to river. A pulls out gun. A demands money. B presses alarm. A sees B. B collects money. A sneezes. '], 
	['inheritance', 'cattleDriver', 'A arrives at river. A gets partial inheritance. A rescues cow. A returns with cow. '], 
	['stagecoach', 'tourBus', 'A arrives with Stagecoach. A welcomes B. B tells A to go to the White House. A departs with B. A converses with B. A departs with B. A and B visit a Landmark. A asks B whats next. A and B arrive at White House. '], 
	['fantasy', 'inheritance', 'Monster holds B captive. A slays monster. A rescues B. A meets B. B falls in love with A. A and B kiss. '], 
	['anchorhead', 'catLover', 'A leaves house. A sneezes. '], 
	['catLover', 'pharmacy', 'A begins the day. A leaves. '], 
	['stagecoach', 'inheritance', 'A arrives with Stagecoach. B enters Stagecoach. A departs with B. A converses with B. A attends funeral. A meets B. A refuses inheritance. '], 
	['catLover', 'inheritance', 'A meets B. A goes to bar. A learns about uncle. A feeds cats. A slips. A hits the ground. A refuses inheritance. '], 
	['robbery', 'catLover', 'Cat injures A. A approaches B. B is scared. A pulls out gun. A demands money. B collects money. B gives A money. A sneezes. '], 
	['tourBus', 'robbery', 'B greets A. A covers face. A arrives at Boarding Location. A approaches B. A tells B to board bus. B is scared. B boards bus. A gets in car. A drives away. '], 
	['anchorhead', 'robbery', 'A pulls out gun. A learns safe combo. A covers face. A gets crypt key. A approaches B. A demands money. A discovers safe. A opens safe. A find coffin. B collects money. B presses alarm. B is scared. B gives A money. A gives B flask. Police arrive. Police arrest A. '], 
	['catLover', 'anchorhead', 'A begins the day. A feeds cats. A gets amulet. A sees frightened cat at river. A gets flask. A opens a puzzle box. A hits the ground. A injures arm. A bandages arm. Cat injures A. A arrives home with cat. A sneezes. '], 
	['cattleDriver', 'pharmacy', 'A begins the day. A rides horse. A smacks saddle. A slips. A hits the ground. A finds a frightened cow. A leaves. '], 
	['robbery', 'stagecoach', 'A approaches B. B enters Stagecoach. B tells A to go to the White House. A covers face. A departs with B. A informs B of arrival. A pulls out gun. A and B arrive at White House. '], 
	['movie', 'inheritance', "A drives to B's house. A meets B. A refuses inheritance. "], 
	['tourBus', 'cattleDriver', 'A slips. A tells B to board bus. A hits the ground. B boards bus. A welcomes B. A departs with B. A and B visit a Landmark. '], 
	['cattleDriver', 'robbery', 'A begins the day. A covers face. A gets in car. A drives away. '], 
	['fantasy', 'catLover', 'Monster holds B captive. A slays monster. A rescues cat. A and B kiss. Cat injures A. B falls in love with A. A and B live happily ever after. '], 
	['cattleDriver', 'inheritance', 'A learns about uncle. A goes to bar. A rides horse. A smacks saddle. A slips. A arrives at river. A finds a frightened cow. A attends funeral. A gets partial inheritance. A meets B. A collects inheritance. '], 
	['cattleDriver', 'catLover', 'A begins the day. A hits the ground. A injures arm. A bandages arm. A smacks saddle. A slips. A arrives at river. A walks to river. A sees frightened cat at river. A puts on gloves. A rescues cat. Cat injures A. A arrives home with cat. A sneezes. '], 
	['tourBus', 'catLover', 'A arrives at Boarding Location. A walks to river. A sees frightened cat at river. A puts on gloves. A rescues cat. Cat injures A. B boards bus. A welcomes B. A departs with B. A sneezes. '], 
	['fantasy', 'movie', "Monster holds B captive. A slays monster. B falls in love with A. A drives to B's house. A and B kiss. A and B get married. A and B live happily ever after. "], 
	['fantasy', 'cattleDriver', 'Monster holds B captive. A slays monster. A bandages arm. B falls in love with A. A and B kiss. A and B get married. A and B live happily ever after. '], 
	['movie', 'anchorhead', 'A meets B. A shows B skull. A drives to theater. A find coffin. A gets skull. A opens safe. A and B buy drinks. A and B enter the theater. A and B buy popcorn. A and B sit down. Movie begins. A gets flask. A and B talk. A and B enjoy the movie. A and B kiss. Movie ends. A and B leave the theater. A and B walk to car. A and B hold hands. B says goodbye to A. '], 
	['fantasy', 'pharmacy', 'Monster holds B captive. A leaves. '], 
	['fantasy', 'cattleDriver', 'Monster holds B captive. A slays monster. A rescues B. B falls in love with A. A and B kiss. A arrives at river. A finds a frightened cow. A rescues cow. A returns with cow. '], 
	['stagecoach', 'tourBus', 'A and B visit a Landmark. B enters Stagecoach. B tells A to go to the White House. A departs with B. A and B arrive at White House. '], 
	['robbery', 'anchorhead', 'A meets B. A covers face. A leaves house. A learns safe combo. A finds secret observatory. A discovers safe. A gets crypt key. A find coffin. A finds magic shop. A approaches B. A gets flask. A gets amulet. A gives B amulet. B is scared. A gets skull. A shows B skull. B tells A about sewer. A discovers book in sewer. '], 
	['stagecoach', 'pharmacy', 'A arrives with Stagecoach. B asks for prescription. A produces prescription. B checks prescription. B enters Stagecoach. A pays cash. A takes receipt. A takes change. A leaves. '], 
	['cattleDriver', 'stagecoach', 'A begins the day. A arrives with Stagecoach. A smacks saddle. A slips. B tells A to go to the White House. A and B arrive at White House. '], 
	['anchorhead', 'catLover', 'A leaves house. A injures arm. A gets crypt key. A bandages arm. A meets B. A find coffin. A rescues cat. A finds secret observatory. A discovers safe. A gets flask. A gets skull. Cat injures A. A arrives home with cat. A sneezes. '], 
	['robbery', 'cattleDriver', 'A approaches B. A pulls out gun. B is scared. A arrives at river. A rides horse. A finds a frightened cow. A demands money. B collects money. A rescues cow. A returns with cow. '], 
	['stagecoach', 'pharmacy', 'A produces prescription. A orders drugs. B checks prescription. B delivers drugs. A swipes a card. A takes receipt. B enters Stagecoach. B tells A to go to the White House. A departs with B. A informs B of arrival. A converses with B. A and B arrive at White House. '], 
	['stagecoach', 'cattleDriver', 'A arrives with Stagecoach. A waits. B enters Stagecoach. B tells A to go to the White House. A departs with B. A injures arm. A informs B of arrival. A rescues cow. A returns with cow. '], 
	['stagecoach', 'movie', "A drives to B's house. A meets B. A drives to theater. B tells A to go to the White House. A departs with B. B says goodbye to A. "], 
	['movie', 'robbery', "A drives to B's house. B greets A. A meets B. A approaches B. A pulls out gun. B is scared. A drives to theater. A parks car. A buys tickets. A and B buy popcorn. A covers face. A demands money. A and B enter the theater. A and B buy drinks. B presses alarm. B collects money. A and B sit down. B gives A money. A gets in car. A drives away. "], 
	['cattleDriver', 'stagecoach', 'A begins the day. A rides horse. A smacks saddle. A slips. B enters Stagecoach. A hits the ground. B tells A to go to the White House. A injures arm. A departs with B. A converses with B. A informs B of arrival. A and B arrive at White House. '], 
	['tourBus', 'pharmacy', 'A swipes a card. A takes receipt. A tells B to board bus. B boards bus. A leaves. '], 
	['stagecoach', 'pharmacy', 'A arrives with Stagecoach. B asks for prescription. A produces prescription. B checks prescription. B delivers drugs. A swipes a card. A takes receipt. A departs with B. A informs B of arrival. A and B arrive at White House. '], 
	['cattleDriver', 'pharmacy', 'A begins the day. A leaves. '], 
	['robbery', 'stagecoach', 'A informs B of arrival. B tells A to go to the White House. A approaches B. A covers face. A and B arrive at White House. '], 
	['fantasy', 'inheritance', 'Monster holds B captive. A slays monster. A attends funeral. A meets B. A refuses inheritance. '], 
	['anchorhead', 'fantasy', 'A leaves house. A discovers safe. A learns safe combo. A and B get married. A finds secret observatory. A opens safe. A and B live happily ever after. '], 
	['inheritance', 'cattleDriver', 'A learns about uncle. A rescues cow. A gets partial inheritance. A returns with cow. '], 
	['tourBus', 'stagecoach', 'A arrives at Boarding Location. A tells B to board bus. B boards bus. A departs with B. A informs B of arrival. A and B arrive at White House. '], 
	['robbery', 'inheritance', 'A gets partial inheritance. B is scared. A goes to bar. A sees B. A waits in line. A pulls out gun. A learns about uncle. B presses alarm. Police arrive. B collects money. B gives A money. A refuses inheritance. '], 
	['inheritance', 'robbery', 'A learns about uncle. A attends funeral. B greets A. A covers face. A goes to bar. A gets partial inheritance. A approaches B. A meets B. B is scared. A pulls out gun. A collects inheritance. '], 
	['tourBus', 'robbery', 'A covers face. A arrives at Boarding Location. A approaches B. B collects money. B gives A money. '], 
	['cattleDriver', 'tourBus', 'A begins the day. A rides horse. A smacks saddle. A slips. A departs with B. A asks B whats next. A injures arm. A bandages arm. A finds a frightened cow. A and B visit a Landmark. A and B arrive at Boarding Location. '], 
	['pharmacy', 'catLover', "A orders drugs. B asks for prescription. A can't produce prescription. A walks to river. A sees frightened cat at river. A puts on gloves. A rescues cat. Cat injures A. B delivers drugs. A leaves. "], 
	['anchorhead', 'robbery', 'A approaches B. A pulls out gun. B is scared. A demands money. B collects money. B presses alarm. B gives A money. Police arrive. A leaves house. A covers face. A gets in car. Police arrest A. '], 
	['tourBus', 'cattleDriver', 'A arrives at Boarding Location. A tells B to board bus. B boards bus. A welcomes B. A departs with B. A and B visit a Landmark. A arrives at river. A finds a frightened cow. A rescues cow. A returns with cow. '], 
	['inheritance', 'catLover', 'A gets partial inheritance. A feeds cats. A slips. A sees frightened cat at river. A walks to river. A puts on gloves. A rescues cat. Cat injures A. A hits the ground. A injures arm. A bandages arm. A arrives home with cat. A meets B. A refuses inheritance. '], 
	['movie', 'tourBus', "A drives to B's house. A welcomes B. A departs with B. A and B visit a Landmark. A tells B to board bus. B boards bus. A and B arrive at Boarding Location. "], 
	['movie', 'inheritance', "A drives to B's house. A meets B. A drives to theater. A parks car. A buys tickets. A and B buy popcorn. A and B buy drinks. A and B enter the theater. A and B sit down. Movie begins. A and B talk. A learns about uncle. A and B enjoy the movie. A and B hold hands. A and B kiss. Movie ends. A and B leave the theater. A and B walk to car. B says goodbye to A. "], 
	['fantasy', 'robbery', 'Monster holds B captive. Police arrive. Police arrest A. '], 
	['tourBus', 'pharmacy', "A produces prescription. B checks prescription. B delivers drugs. A swipes a card. A takes receipt. A tells B to board bus. B boards bus. A departs with B. A and B visit a Landmark. A leaves. "], 
	['anchorhead', 'robbery', 'A leaves house. A gets crypt key. A approaches B. B greets A. A finds magic shop. B is scared. A pulls out gun. A discovers safe. A learns safe combo. A opens safe. A demands money. A finds secret observatory. B collects money. B presses alarm. B gives A money. A covers face. Police arrive. A gets in car. Police arrest A. '], 
	['stagecoach', 'fantasy', 'B falls in love with A. A rescues B. A and B kiss. A and B get married. B tells A to go to the White House. A and B live happily ever after. '], 
	['anchorhead', 'inheritance', 'A leaves house. A collects inheritance. '], 
	['stagecoach', 'movie', 'A arrives with Stagecoach. B says goodbye to A. '], 
	['fantasy', 'tourBus', 'Monster holds B captive. A slays monster. A rescues B. B falls in love with A. A and B arrive at Boarding Location. '], 
	['cattleDriver', 'anchorhead', 'A begins the day. B tells A about sewer. A discovers book in sewer. '], 
	['fantasy', 'catLover', 'Monster holds B captive. A slays monster. A rescues B. B falls in love with A. A and B kiss. A sneezes. '], 
	['robbery', 'fantasy', 'A and B kiss. A covers face. B gives A money. A slays monster. A and B get married. A and B live happily ever after. '], 
	['inheritance', 'cattleDriver', 'A goes to bar. A learns about uncle. A gets partial inheritance. A rides horse. A meets B. A smacks saddle. A collects inheritance. '], 
	['tourBus', 'pharmacy', 'A swipes a card. A tells B to board bus. A takes receipt. B boards bus. A leaves. '], 
	['movie', 'catLover', "A drives to B's house. A meets B. A drives to theater. A parks car. A buys tickets. Cat injures A. A injures arm. A bandages arm. A arrives home with cat. A sneezes. "], 
	['inheritance', 'catLover', 'A injures arm. A bandages arm. A learns about uncle. A gets partial inheritance. A arrives home with cat. A sneezes. '], 
	['catLover', 'pharmacy', "A begins the day. A feeds cats. A walks to river. A sees frightened cat at river. A puts on gloves. A rescues cat. B refuses to sell. A hits the ground. A leaves. "], 
	['movie', 'fantasy', "A drives to B's house. A meets B. A drives to theater. A parks car. A buys tickets. A and B kiss. A and B buy popcorn. A and B buy drinks. A and B get married. A and B live happily ever after. "], 
	['cattleDriver', 'robbery', 'A approaches B. A pulls out gun. B is scared. B greets A. A covers face. A drives away. '], 
	['catLover', 'pharmacy', 'A begins the day. A feeds cats. A leaves. '], 
	['cattleDriver', 'pharmacy', 'A begins the day. A rides horse. A smacks saddle. A pays cash. A takes receipt. A leaves. '], 
	['inheritance', 'robbery', 'A goes to bar. A enters bank. A waits in line. A learns about uncle. A attends funeral. A sees B. A approaches B. A pulls out gun. A demands money. B is scared. A gets in car. A drives away. '], 
	['anchorhead', 'pharmacy', "A leaves house. A finds secret observatory. A discovers safe. A finds magic shop. A gets flask. A learns safe combo. A opens safe. A produces prescription. A gets crypt key. B checks prescription. B delivers drugs. A find coffin. A gets skull. A leaves. "], 
	['pharmacy', 'inheritance', 'A orders drugs. A attends funeral. A meets B. A refuses inheritance. '], 
	['cattleDriver', 'fantasy', 'A begins the day. A rides horse. A smacks saddle. A slips. A arrives at river. A and B get married. A and B live happily ever after. '], 
	['cattleDriver', 'catLover', 'A begins the day. A feeds cats. A slips. A smacks saddle. A sees frightened cat at river. Cat injures A. A sneezes. '], 
	['fantasy', 'pharmacy', 'Monster holds B captive. A slays monster. B falls in love with A. A rescues B. A and B kiss. A leaves. '], 
	['robbery', 'tourBus', 'A approaches B. A and B visit a Landmark. A asks B whats next. A pulls out gun. A departs with B. A enters bank. A scans bank. A covers face. A waits in line. B collects money. B gives A money. A tells B to board bus. A drives away. '], 
	['pharmacy', 'inheritance', "A gets partial inheritance. A goes to bar. A orders drugs. B asks for prescription. A can't produce prescription. B refuses to sell. A leaves. "], 
	['inheritance', 'robbery', 'B greets A. A gets partial inheritance. A attends funeral. A meets B. A approaches B. A enters bank. A sees B. A collects inheritance. '], 
	['fantasy', 'robbery', 'Monster holds B captive. A covers face. A approaches B. B is scared. A pulls out gun. A demands money. B presses alarm. B collects money. A waits in line. Police arrive. B falls in love with A. Police arrest A. '], 
	['cattleDriver', 'anchorhead', 'A begins the day. A finds magic shop. A find coffin. A leaves house. A hits the ground. A gets skull. A learns safe combo. A gets amulet. A gets flask. A gets crypt key. A discovers safe. A opens safe. A meets B. A gives B flask. A shows B skull. A finds secret observatory. A opens a puzzle box. A gives B amulet. A sees evil god. '], 
	['stagecoach', 'fantasy', 'A slays monster. B falls in love with A. B enters Stagecoach. A departs with B. A and B kiss. A and B get married. A and B live happily ever after. '], 
	['stagecoach', 'movie', "A arrives with Stagecoach. B enters Stagecoach. B tells A to go to the White House. A departs with B. A drives to B's house. A converses with B. A and B arrive at White House. "], 
	['fantasy', 'anchorhead', 'Monster holds B captive. A slays monster. B falls in love with A. A rescues B. A sees evil god. '], 
	['pharmacy', 'anchorhead', 'A orders drugs. B asks for prescription. B tells A about sewer. B checks prescription. A discovers book in sewer. '], 
	['inheritance', 'fantasy', 'A goes to bar. Monster holds B captive. A slays monster. B falls in love with A. A rescues B. A and B kiss. A and B get married. A attends funeral. A and B live happily ever after. '], 
	['anchorhead', 'robbery', 'A waits in line. A discovers safe. A gets in car. A approaches B. B greets A. A pulls out gun. B is scared. A demands money. B presses alarm. B collects money. Police arrive. A gets crypt key. A finds magic shop. Police arrest A. ']]
	return twoStories

def GetThreeStoryCombos():
	threeStories = [['anchorhead', 'inheritance', 'fantasy', 'A leaves house. Monster holds B captive. A learns about uncle. A slays monster. A gets amulet. A discovers safe. A rescues B. A goes to bar. A collects inheritance. '], 
	['anchorhead', 'catLover', 'movie', 'A leaves house. A parks car. Cat injures A. A finds secret observatory. A finds magic shop. A puts on gloves. A drives to theater. A meets B. A walks to river. B says goodbye to A. '], 
	['robbery', 'fantasy', 'tourBus', 'A and B kiss. A covers face. A approaches B. A and B get married. A departs with B. A welcomes B. A and B live happily ever after. '], 
	['inheritance', 'tourBus', 'cattleDriver', 'A rescues cow. A attends funeral. A rides horse. A smacks saddle. A meets B. A returns with cow. '], 
	['robbery', 'inheritance', 'fantasy', 'A attends funeral. A approaches B. A and B kiss. A pulls out gun. A enters bank. A waits in line. B is scared. A sees B. A demands money. A collects inheritance. '], 
	['tourBus', 'movie', 'inheritance', 'A learns about uncle. A arrives at Boarding Location. B says goodbye to A. '], 
	['inheritance', 'cattleDriver', 'pharmacy', 'A injures arm. A gets partial inheritance. A bandages arm. A meets B. A leaves. '], 
	['inheritance', 'catLover', 'pharmacy', 'A begins the day. A feeds cats. A walks to river. A sees frightened cat at river. A goes to bar. A pays cash. A takes receipt. A learns about uncle. A puts on gloves. A leaves. '], 
	['robbery', 'anchorhead', 'tourBus', 'A asks B whats next. A and B visit a Landmark. A talks to B. A discovers safe. A gets skull. A arrives at Boarding Location. A covers face. A demands money. B presses alarm. B collects money. B is scared. B gives A money. Police arrive. A leaves bank. Police arrest A. '], 
	['robbery', 'pharmacy', 'tourBus', "A approaches B. A covers face. B is scared. A orders drugs. B asks for prescription. A pulls out gun. A can't produce prescription. A demands money. B collects money. B gives A money.B delivers drugs. A departs with B. A tells B to board bus. B boards bud. A leaves. "], 
	['stagecoach', 'robbery', 'anchorhead', 'B greets A. A gives B flask. A approaches B. A find coffin. A pulls out gun. A gets skull. B is scared. A talks to B. A waits. A informs B of arrival. A shows B skull. A demands money. Police arrive. Police arrest A. '], 
	['fantasy', 'stagecoach', 'inheritance', 'A goes to bar. Monster holds B captive. A converses with B. '], 
	['robbery', 'pharmacy', 'catLover', 'A enters bank. A arrives home with cat. A approaches B. A pulls out gun. A demands money. A leaves. '], 
	['catLover', 'tourBus', 'cattleDriver', 'A begins the day. A feeds cats. A slips. A hits the ground. A walks to river. A departs with B. B boards bus. A finds a frightened cow. A rescues cow. A returns with cow. '],
	['cattleDriver', 'inheritance', 'anchorhead', 'A begins the day. A goes to bar. A gets amulet. A smacks saddle. A gives B flask. A learns about uncle. A talks to B. A attends funeral. A discovers safe. A finds a frightened cow. A learns safe combo. A opens safe. A returns with cow. '], 
	['inheritance', 'robbery', 'tourBus', 'A covers face. A learns about uncle. A sees B. A approaches B. A departs with B. B is scared. A and B visit a Landmark. B collects money. A and B arrive at Boarding Location. '], 
	['tourBus', 'robbery', 'fantasy', 'A arrives at Boarding Location. A rescues B. A tells B to board bus. B boards bus. B falls in love with A. A covers face. A approaches B. A pulls out gun. B is scared. A demands money. A and B kiss. B presses alarm. Police arrive. Police arrest A. '], 
	['robbery', 'catLover', 'cattleDriver', 'A feeds cats. A injures arm. A slips. A arrives at river. A puts on gloves. A injures arm. A sees B. A slips. A rescues cow. A rides horse. A returns with cow. '], 
	['movie', 'robbery', 'stagecoach', 'A covers face. A demands money. B collects money. A drives to theater. A departs with B. B presses alarm. A converses with B. A parks car. A buys tickets. Police arrive. A approaches B. A pulls out gun. A and B buy popcorn and soda. A and B enter the theater. Police arrest A. '], 
	['stagecoach', 'inheritance', 'pharmacy', "A arrives with Stagecoach. B asks for prescription. A can't produce prescription. B refuses to sell. A attends funeral. A leaves. "], 
	['movie', 'anchorhead', 'robbery', 'A drives to theater. A covers face. A gets amulet. A scans bank. B tells A about sewer. A gives B amulet. A leaves bank. A discovers book in sewer. '], 
	['movie', 'robbery', 'cattleDriver', "A drives to B's house. A approaches B. A rides horse. A smacks saddle. A arrives at river. A finds a frightened cow. A slips. A hits the ground. A rescues cow. A injures arm. A bandages arm. B greets A. A demands money. B collects money. B gives A money. B is scared. B presses alarm. A covers face. Police arrive. Police arrest A. "], 
	['robbery', 'tourBus', 'stagecoach', 'B tells A to go to the White House. A asks B whats next. A waits. A gets in car. A approaches B. A departs with B. A drives away. '], 
	['inheritance', 'stagecoach', 'movie', 'A gets partial inheritance. A learns about uncle. A departs with B. B says goodbye to A. '], 
	['anchorhead', 'inheritance', 'pharmacy', 'A leaves house. A gets crypt key. A meets B. B asks for prescription. A leaves. '], 
	['robbery', 'catLover', 'pharmacy', "A can't produce prescription. B refuses to sell. A slips. A approaches B. B is scared. A injures arm. A leaves. "], 
	['tourBus', 'catLover', 'anchorhead', 'A arrives at Boarding Location. A gives B flask. A talks to B. A arrives home with cat. A sneezes. '], 
	['anchorhead', 'catLover', 'cattleDriver', 'A leaves house. A injures arm. A meets B. A arrives at river. A discovers book in sewer. '], 
	['pharmacy', 'anchorhead', 'fantasy', 'A leaves house. A gets crypt key. A slays monster. A learns safe combo. A discovers safe. A leaves. '], 
	['anchorhead', 'cattleDriver', 'catLover', 'A leaves house. A walks to river. A slips. A hits the ground. A returns with cow. '], 
	['robbery', 'pharmacy', 'anchorhead', 'A takes receipt. A shows B skull. A drives away. '], 
	['tourBus', 'stagecoach', 'inheritance', 'A arrives at Boarding Location. A departs with B. A gets partial inheritance. A converses with B. A informs B of arrival. A collects inheritance. '], 
	['anchorhead', 'pharmacy', 'tourBus', 'A leaves house. A departs with B. A asks B whats next. A leaves. '],
	['stagecoach', 'fantasy', 'movie', 'A arrives with Stagecoach. A and B get married. A and B leave the theater. A and B live happily ever after. '], 
	['movie', 'stagecoach', 'pharmacy', 'A waits. A meets B. B tells A to go to the White House. A parks car. A departs with B. B asks for prescription. A converses with B. A produces prescription. B delivers drugs. A informs B of arrival. A swipes a card. A buys tickets. A leaves. '], 
	['anchorhead', 'fantasy', 'stagecoach', 'A leaves house. A meets B. A and B kiss. B tells A to go to the White House. B falls in love with A. A gets crypt key. A discovers safe. A finds magic shop. A and B get married. A gets amulet. A informs B of arrival.  A and B arrive at White House. '], 
	['cattleDriver', 'fantasy', 'tourBus', 'A begins the day. A departs with B. A and B live happily ever after. '], 
	['anchorhead', 'catLover', 'pharmacy', "A leaves house. A takes change. A meets B. A injures arm. A hits the ground. A gives B flask. A orders drugs. A finds secret observatory. Cat injures A. A gets crypt key. B asks for prescription. A can't produce prescription. B refuses to sell. A leaves. "], 
	['anchorhead', 'inheritance', 'fantasy', 'A gets partial inheritance. A and B kiss. A finds secret observatory. A gets flask. A and B get married. A finds magic shop. Monster holds B captive. A learns about uncle. A slays monster. A rescues B. A gets amulet. A attends funeral. A meets B. A learns safe combo. A gives B flask. A gives B amulet. B tells A about sewer. A discovers book in sewer. '], 
	['catLover', 'stagecoach', 'cattleDriver', 'A rescues cow. A feeds cats. A informs B of arrival. A walks to river. A sees frightened cat at river. A arrives with Stagecoach. A slips. A hits the ground. B enters Stagecoach. A returns with cow. '], 
	['stagecoach', 'robbery', 'catLover', 'A arrives home with cat. Cat injures A. B gives A money.  A pulls out gun. B is scared. A departs with B. A demands money. B presses alarm. A covers face. B collects money. Police arrive. A sneezes. '], 
	['robbery', 'stagecoach', 'fantasy', 'B greets A. A approaches B. B is scared. A covers face. B falls in love with A. A departs with B. A and B live happily ever after. '], 
	['anchorhead', 'robbery', 'movie', 'A uses the bathroom. A drives to theater. B greets A. A approaches B. A meets B. A enters bank. A find coffin. A gets in car. A sees B. A drives away. '], 
	['catLover', 'robbery', 'pharmacy', 'A begins the day. B greets A. A approaches B. A feeds cats. A covers face. B refuses to sell. A leaves. '], 
	['robbery', 'tourBus', 'fantasy', 'A enters bank. A covers face. A tells B to board bus. A scans bank. B boards bus. A and B live happily ever after. '], 
	['fantasy', 'movie', 'cattleDriver', 'Monster holds B captive. A uses the bathroom. A rescues B. B falls in love with A. A parks car. A bandages arm. A and B enter the theater. A and B live happily ever after. '],
	['inheritance', 'fantasy', 'movie', 'A meets B. A rescues B. A buys tickets. A attends funeral. A and B buy popcorn and soda. A refuses inheritance. '], 
	['fantasy', 'robbery', 'cattleDriver', 'A hits the ground. Monster holds B captive. A slays monster. A covers face. B is scared. A approaches B. A rescues B. A pulls out gun. A and B kiss. A and B live happily ever after. '], 
	['cattleDriver', 'inheritance', 'robbery', 'A begins the day. A approaches B. B is scared. A covers face. A smacks saddle. A enters bank. A waits in line. B greets A. A scans bank. A injures arm. A sees B. A collects inheritance. '], 
	['catLover', 'inheritance', 'movie', 'A parks car. A meets B. A buys tickets. A and B buy drinks. A and B buy popcorn. A and B enter the theater. A and B sit down. Movie begins. A uses the bathroom. A and B talk. A and B hold hands. A and B enjoy the movie. Movie ends. A and B leave the theater. A and B walk to car. A and B kiss. A learns about uncle. A begins the day. A drives to theater. A refuses inheritance. '], 
	['fantasy', 'cattleDriver', 'inheritance', 'Monster holds B captive. A learns about uncle. A goes to bar. A meets B. B falls in love with A. A rescues B. A hits the ground. A refuses inheritance. '], 
	['tourBus', 'anchorhead', 'stagecoach', 'A leaves house. A gets skull. A gets crypt key. A gets flask. A departs with B. A meets B. A informs B of arrival. A shows B skull. A converses with B. B enters Stagecoach. A learns safe combo. B boards bus. A gives B flask. A sees evil god. '], 
	['stagecoach', 'fantasy', 'anchorhead', 'A arrives with Stagecoach. A opens a puzzle box. A rescues B. B enters Stagecoach. B tells A to go to the White House. A departs with B. A informs B of arrival. A learns safe combo. A gives B amulet. B tells A about sewer. B falls in love with A. A and B kiss. A discovers book in sewer. '], 
	['anchorhead', 'cattleDriver', 'movie', 'A leaves house. A learns safe combo. A finds secret observatory. A discovers safe. A gets crypt key. A meets B. A slips. A hits the ground. A bandages arm. A gives B flask. A sees evil god. Movie ends. '], 
	['anchorhead', 'robbery', 'pharmacy', 'A takes receipt. A approaches B. A leaves house. A covers face. A finds secret observatory. A leaves. '], 
	['inheritance', 'robbery', 'anchorhead', 'A leaves house. A covers face. A enters bank. A sees B. A learns safe combo. A approaches B. A pulls out gun. A waits in line. A finds magic shop. B is scared. A demands money. A gets crypt key. B collects money. A discovers safe. A scans bank. B presses alarm. B gives A money. A gets partial inheritance. A find coffin. A gets skull. A opens safe. A opens a puzzle box. B tells A about sewer. A sees evil god. '], 
	['pharmacy', 'cattleDriver', 'stagecoach', 'A orders drugs. B asks for prescription. A produces prescription. B checks prescription. B delivers drugs. A arrives at river. A informs B of arrival. A bandages arm. '], 
	['stagecoach', 'robbery', 'catLover', 'Cat injures A. A pulls out gun. A bandages arm. A approaches B. A arrives home with cat. B is scared. B collects money. A covers face. B presses alarm. Police arrive. B enters Stagecoach. B gives A money. Police arrest A. '], 
	['stagecoach', 'inheritance', 'anchorhead', 'A arrives with Stagecoach. A gets flask. A attends funeral. A opens safe. A finds magic shop. A gets amulet. A refuses inheritance. '], 
	['tourBus', 'pharmacy', 'anchorhead', 'A arrives at Boarding Location. A tells B to board bus. B asks for prescription. A opens a puzzle box. B checks prescription. A welcomes B. B delivers drugs. A gets amulet. A talks to B. A gets skull. A takes receipt. A asks B whats next. A leaves. '], 
	['pharmacy', 'inheritance', 'tourBus', "A orders drugs. B asks for prescription. A learns about uncle. A can't produce prescription. B boards bus. A leaves. "], 
	['fantasy', 'anchorhead', 'catLover', 'Monster holds B captive. A opens safe. A rescues B. A gets crypt key. A find coffin. A sneezes. '], 
	['fantasy', 'tourBus', 'anchorhead', 'Monster holds B captive. A and B visit a Landmark. A sees evil god. '], 
	['movie', 'stagecoach', 'catLover', "A drives to B's house. A feeds cats. A informs B of arrival. "], 
	['anchorhead', 'cattleDriver', 'stagecoach', 'A leaves house. A meets B. B tells A to go to the White House. A informs B of arrival. A gets flask. A converses with B. A finds magic shop. A injures arm. A bandages arm. A waits. A learns safe combo. A and B arrive at White House. A rescues cow. '], 
	['robbery', 'catLover', 'anchorhead', 'A leaves house. A finds magic shop. A discovers safe. A learns safe combo. A gets crypt key. A gives B amulet. A find coffin. A gets skull. A opens safe. B greets A. B tells A about sewer. A hits the ground. B is scared. A discovers book in sewer. '], 
	['robbery', 'inheritance', 'tourBus', 'A learns about uncle. A approaches B. A and B arrive at Boarding Location. '], 
	['cattleDriver', 'stagecoach', 'pharmacy', 'A rides horse. A smacks saddle. A swipes a card. A waits. A injures arm. A leaves. '], 
	['fantasy', 'catLover', 'pharmacy', 'Monster holds B captive. Cat injures A. B delivers drugs. A pays cash. B refuses to sell. A leaves. '], 
	['stagecoach', 'fantasy', 'catLover', 'A arrives with Stagecoach. A waits. B enters Stagecoach. Monster holds B captive. A departs with B. A bandages arm. A begins the day. A feeds cats. A walks to river. A slips. A sees frightened cat at river. A puts on gloves. A rescues cat. A hits the ground. A slays monster. A injures arm. A converses with B. A rescues B. B falls in love with A. A and B kiss. Cat injures A. A arrives home with cat. A sneezes. '], 
	['cattleDriver', 'stagecoach', 'anchorhead', 'A meets B. A rides horse. A smacks saddle. A slips. A shows B skull. A injures arm. A gives B flask. A talks to B. A arrives at river. A informs B of arrival. '], 
	['cattleDriver', 'robbery', 'stagecoach', 'A begins the day. A approaches B. B is scared. A pulls out gun. A demands money. B tells A to go to the White House. A departs with B. B presses alarm. A converses with B. A rides horse. Police arrive. Police arrest A. '], 
	['fantasy', 'movie', 'cattleDriver', 'Monster holds B captive. A slays monster. A rescues B. A rides horse. A smacks saddle. A arrives at river. B falls in love with A. A and B buy drinks. A finds a frightened cow. A rescues cow. A returns with cow. '], 
	['inheritance', 'fantasy', 'cattleDriver', 'A slays monster. B falls in love with A. A attends funeral. A rescues B. A finds a frightened cow. A rescues cow. A learns about uncle. A returns with cow. '], 
	['pharmacy', 'catLover', 'inheritance', 'A learns about uncle. A injures arm. B asks for prescription. A produces prescription. B checks prescription. B delivers drugs. A pays cash. '], 
	['anchorhead', 'movie', 'catLover', "A leaves house. A gets flask. A finds magic shop. A meets B. A drives to B's house. A discovers safe. A find coffin. A learns safe combo. Cat injures A. A walks to river. B says goodbye to A. "], 
	['stagecoach', 'inheritance', 'pharmacy', "A arrives with Stagecoach. B enters Stagecoach. A orders drugs. B asks for prescription. A can't produce prescription. B refuses to sell. A goes to bar. A leaves. "], 
	['robbery', 'anchorhead', 'pharmacy', 'A approaches B. B greets A. A gives B amulet. B is scared. A covers face. B tells A about sewer. A leaves. '], 
	['stagecoach', 'catLover', 'robbery', 'A covers face. B collects money. B tells A to go to the White House. A walks to river. A hits the ground. A sees frightened cat at river. A pulls out gun. A puts on gloves. A converses with B. A demands money. B presses alarm. Police arrive. A injures arm. Police arrest A. '], 
	['stagecoach', 'pharmacy', 'fantasy', 'A arrives with Stagecoach. B delivers drugs. A pays cash. A takes receipt. A and B get married. A leaves. '], 
	['tourBus', 'stagecoach', 'cattleDriver', 'A arrives at Boarding Location. A hits the ground. B boards bus. A welcomes B. A injures arm. A bandages arm. A departs with B. A converses with B. A rescues cow. A returns with cow. '], 
	['cattleDriver', 'robbery', 'fantasy', 'A begins the day. A and B get married. A approaches B. A and B live happily ever after. '], 
	['tourBus', 'cattleDriver', 'inheritance', 'A gets partial inheritance. A tells B to board bus. A smacks saddle. A learns about uncle. A attends funeral. A slips. A hits the ground. A arrives at river. A collects inheritance. '],
	['fantasy', 'cattleDriver', 'anchorhead', 'A shows B skull. A rescues cow. A discovers safe. A gives B amulet. A rescues B. B tells A about sewer. A and B kiss. A discovers book in sewer. '], 
	['stagecoach', 'cattleDriver', 'fantasy', 'A arrives with Stagecoach. B enters Stagecoach. B tells A to go to the White House. A departs with B. A informs B of arrival. A arrives at river. A slays monster. A and B get married. A and B live happily ever after. '], 
	['anchorhead', 'stagecoach', 'inheritance', 'A leaves house. A attends funeral. A gets partial inheritance. A converses with B. A meets B. B tells A to go to the White House. A learns about uncle. A goes to bar. A and B arrive at White House. '], 
	['inheritance', 'anchorhead', 'tourBus', 'A leaves house. A goes to bar. A departs with B. A finds secret observatory. A discovers safe. A learns safe combo. B boards bus. A meets B. A gets crypt key. A gets flask. A finds magic shop. A gets amulet. A and B visit a Landmark. A gives B amulet. A find coffin. A tells B to board bus. A opens safe. B tells A about sewer. A opens a puzzle box. A and B arrive at Boarding Location. '], 
	['cattleDriver', 'tourBus', 'stagecoach', 'A and B visit a Landmark. A asks B whats next. A rides horse. A converses with B. A smacks saddle. A arrives at river. A finds a frightened cow. B enters Stagecoach. A departs with B. A and B arrive at Boarding Location. '], 
	['stagecoach', 'fantasy', 'inheritance', 'A and B kiss. A waits. B enters Stagecoach. A learns about uncle. A collects inheritance. '], 
	['stagecoach', 'inheritance', 'movie', 'A arrives with Stagecoach. B enters Stagecoach. B tells A to go to the White House. A goes to bar. A uses the bathroom. A meets B. '], 
	['movie', 'robbery', 'stagecoach', 'A arrives with Stagecoach. A meets B. B enters Stagecoach. A gets in car. A drives away. '], 
	['tourBus', 'stagecoach', 'fantasy', 'A converses with B. A tells B to board bus. B boards bus. A and B get married. A departs with B. A and B kiss. A and B live happily ever after. '], 
	['inheritance', 'movie', 'cattleDriver', 'A gets partial inheritance. A injures arm. A arrives at river. A finds a frightened cow. A rescues cow. A bandages arm. A learns about uncle. A attends funeral. '], 
	['inheritance', 'cattleDriver', 'tourBus', 'A learns about uncle. A goes to bar. A gets partial inheritance. A meets B. A and B visit a Landmark. A asks B whats next. A injures arm. A bandages arm. A departs with B. A collects inheritance. '], 
	['movie', 'inheritance', 'catLover', "A drives to B's house. A injures arm. A bandages arm. A meets B. A hits the ground. A slips. A collects inheritance. "],  
	['anchorhead', 'tourBus', 'movie', 'A leaves house. A meets B. A welcomes B. B says goodbye to A. '], 
	['tourBus', 'fantasy', 'stagecoach', 'A arrives at Boarding Location. A and B kiss. B tells A to go to the White House. A departs with B. A and B visit a Landmark. A converses with B. A informs B of arrival. A and B arrive at White House. '], 
	['stagecoach', 'anchorhead', 'pharmacy', 'A meets B. A waits. B enters Stagecoach. B refuses to sell. A leaves. '], 
	['robbery', 'fantasy', 'inheritance', 'A rescues B. A goes to bar. A and B kiss. A gets partial inheritance. A enters bank. A refuses inheritance. '], 
	['fantasy', 'pharmacy', 'movie', "B asks for prescription. A can't produce prescription. B refuses to sell. A slays monster. A uses the bathroom. A leaves. "], 
	['fantasy', 'movie', 'pharmacy', "A meets B. A drives to B's house. B falls in love with A. A drives to theater. A leaves. "], 
	['anchorhead', 'fantasy', 'cattleDriver', 'A leaves house. A finds a frightened cow. A and B live happily ever after. '], 
	['inheritance', 'anchorhead', 'robbery', 'A covers face. A approaches B. A gets partial inheritance. B is scared. A pulls out gun. A discovers safe. A enters bank. A demands money. B presses alarm. A sees B. Police arrive. A leaves bank. A gets in car. A refuses inheritance. '], 
	['pharmacy', 'inheritance', 'stagecoach', 'B asks for prescription. B tells A to go to the White House. A attends funeral. A learns about uncle. A and B arrive at White House. '], 
	['inheritance', 'fantasy', 'anchorhead', 'A gets partial inheritance. A goes to bar. A attends funeral. A meets B. A slays monster. A shows B skull. A collects inheritance. '], 
	['anchorhead', 'tourBus', 'catLover', 'A leaves house. A meets B. B boards bus. Cat injures A. A injures arm. A sneezes. '], 
	['cattleDriver', 'stagecoach', 'robbery', 'A begins the day. A approaches B. B greets A. A covers face. A pulls out gun. A rides horse. B is scared. A smacks saddle. A demands money. A converses with B. B collects money. B presses alarm. Police arrive. Police arrest A. '], 
	['tourBus', 'robbery', 'catLover', 'A arrives at Boarding Location. A puts on gloves. A walks to river. A rescues cat. A leaves bank. A arrives home with cat. A tells B to board bus. A waits in line. A drives away. '], 
	['inheritance', 'movie', 'cattleDriver', 'A gets partial inheritance. A injures arm. A parks car. A bandages arm. A arrives at river. A finds a frightened cow. A collects inheritance. '], 
	['cattleDriver', 'stagecoach', 'pharmacy', 'A converses with B. A rides horse. A leaves. '], 
	['pharmacy', 'fantasy', 'anchorhead', 'A orders drugs. A shows B skull. A slays monster. A meets B. B tells A about sewer. A discovers book in sewer. '], 
	['movie', 'cattleDriver', 'fantasy', 'A arrives at river. A finds a frightened cow. A drives to theater. A slays monster. A returns with cow. '], 
	['robbery', 'inheritance', 'tourBus', 'A collects inheritance. A meets B. B greets A. A departs with B. A and B visit a Landmark. '], 
	['tourBus', 'robbery', 'fantasy', 'A leaves bank. A rescues B. A tells B to board bus. B boards bus. A and B kiss. A and B live happily ever after. '], 
	['robbery', 'inheritance', 'movie', 'A learns about uncle. A gets partial inheritance. A meets B. A meets B. B greets A. A refuses inheritance. '], 
	['movie', 'anchorhead', 'cattleDriver', "A drives to B's house. A slips. A gives B amulet. B tells A about sewer. A injures arm. A discovers book in sewer. "],
	['cattleDriver', 'inheritance', 'robbery', 'A begins the day. A approaches B. B is scared. A attends funeral. A meets B. B greets A. A refuses inheritance. '], 
	['movie', 'robbery', 'pharmacy', "A drives to B's house. A covers face. A approaches B. A pulls out gun. B is scared. B collects money. A takes receipt. B gives A money. A leaves. "], 
	['movie', 'inheritance', 'anchorhead', "A drives to B's house. A finds secret observatory. A opens safe. A refuses inheritance. "], 
	['fantasy', 'tourBus', 'cattleDriver', 'A asks B whats next. A slays monster. B falls in love with A. A rescues B. A tells B to board bus. A returns with cow. '], 
	['pharmacy', 'stagecoach', 'inheritance', "A converses with B. A learns about uncle. B asks for prescription. A can't produce prescription. B refuses to sell. A leaves. "]]
	return threeStories

def GetFourStoryCombos():
	fourStories = [['inheritance', 'fantasy', 'stagecoach', 'anchorhead', 'A gets partial inheritance. A slays monster. A shows B skull. A leaves house. A finds secret observatory. A talks to B. A gets crypt key. A finds coffin. B falls in love with A. A gets skull. A finds magic shop. A gets amulet. A converses with B. A learns safe combo. A rescues B. A and B kiss. A gives B amulet. A and B get married. A discovers safe. A and B live happily ever after. '],  
	['robbery', 'stagecoach', 'fantasy', 'cattleDriver', 'A enters bank. A approaches B. A departs with B. A rescues cow. B falls in love with A. A and B get married. '], 
	['stagecoach', 'anchorhead', 'robbery', 'tourBus', 'B greets A. A arrives with Stagecoach. A approaches B. A waits. B is scared. A covers face. A pulls out gun. B tells A about sewer. A demands money. B collects money. B gives A money. A departs with B. A and B visit a Landmark. A asks B whats next. B boards bus. A discovers book in sewer. '],
	['anchorhead', 'tourBus', 'fantasy', 'cattleDriver', 'A begins the day. A finds magic shop. A slays monster. A departs with B. A rescues B. B falls in love with A. A returns with cow. '],
	['tourBus', 'cattleDriver', 'stagecoach', 'movie', 'A arrives with Stagecoach. A rescues cow. B enters Stagecoach. A meets B. A converses with B. A and B arrive at Boarding Location. '], 
	['fantasy', 'stagecoach', 'inheritance', 'tourBus', 'A tells B to board bus. B boards bus. A welcomes B. A departs with B. A slays monster. A converses with B. A refuses inheritance. '], 
	['movie', 'robbery', 'fantasy', 'inheritance', "A attends funeral. A approaches B. A meets B. A covers face. A drives to B's house. A pulls out gun. A demands money. B collects money. B presses alarm. A slays monster. B gives A money. Police arrive. A and B kiss. A and B get married. A and B live happily ever after. "], 
	['fantasy', 'robbery', 'cattleDriver', 'catLover', 'Monster holds B captive. A gets in car. A covers face. A approaches B. B is scared. A pulls out gun. A puts on gloves. A finds a frightened cow. A rescues cat. A rescues cow. A demands money. Cat injures A. B collects money. B presses alarm. Police arrive. Police arrest A. '],
	['fantasy', 'robbery', 'anchorhead', 'movie', 'Monster holds B captive. A talks to B. B greets A. A slays monster. A shows B skull. B says goodbye to A. '], 
	['robbery', 'inheritance', 'catLover', 'stagecoach', 'A covers face. A enters bank. A informs B of arrival. A learns about uncle. A hits the ground. Cat injures A. A sees B. A approaches B. B is scared. A pulls out gun. A demands money. B presses alarm. Police arrive. B collects money. Police arrest A. '], 
	['stagecoach', 'catLover', 'cattleDriver', 'fantasy', 'A smacks saddle. B falls in love with A. A slays monster. A arrives at river. A and B get married. A bandages arm. A finds a frightened cow. A hits the ground. A rescues B. A and B kiss. A bandages arm. A rescues cow. B tells A to go to the White House. A and B arrive at White House. '], 
	['stagecoach', 'tourBus', 'cattleDriver', 'movie', 'A arrives with Stagecoach. A welcomes B. A bandages arm. B enters Stagecoach. A smacks saddle. B says goodbye to A. '], 
	['anchorhead', 'robbery', 'catLover', 'stagecoach', 'A sees frightened cat at river. A departs with B. A converses with B. A puts on gloves. A talks to B. A injures arm. A bandages arm. A rescues cat. A drives away. '], 
	['catLover', 'movie', 'anchorhead', 'stagecoach', 'A begins the day. A feeds cats. A opens a puzzle box. A meets B. A talks to B. A waits. A and B enter the theater. A learns safe combo. B enters Stagecoach. A opens safe. B says goodbye to A. ']
	, ['anchorhead', 'movie', 'inheritance', 'cattleDriver', 'A leaves house. A learns about uncle. A uses the bathroom. A gets flask. A meets B. A gets crypt key. A arrives at river. A rescues cow. A refuses inheritance. '], 
	['movie', 'tourBus', 'inheritance', 'catLover', "Cat injures A. A drives to B's house. A slips. A hits the ground. A asks B whats next. A puts on gloves. A and B buy popcorn and soda. A parks car. A and B enter the theater. A and B sit down. A learns about uncle. Movie begins. A sneezes. "],  
	['fantasy', 'robbery', 'tourBus', 'catLover', 'Monster holds B captive. B greets A. A covers face. A slays monster. B falls in love with A. A rescues B. A demands money. B collects money. A and B visit a Landmark. A injures arm. A bandages arm. A asks B whats next. A departs with B. A sneezes. '], 
	['robbery', 'inheritance', 'anchorhead', 'movie', 'A waits in line. A meets B. Movie ends. A finds secret observatory. A attends funeral. B greets A. A collects inheritance. '], 
	['inheritance', 'cattleDriver', 'anchorhead', 'robbery', 'A gets partial inheritance. A gets skull. A meets B. A finds a frightened cow. A pulls out gun. A rescues cow. A slips. A hits the ground. A bandages arm. A discovers book in sewer. '], 
	['catLover', 'tourBus', 'inheritance', 'pharmacy', 'A asks B whats next. A feeds cats. A learns about uncle. A leaves. '], 
	['robbery', 'fantasy', 'inheritance', 'catLover', 'A sees frightened cat at river. A meets B. A puts on gloves. A approaches B. A rescues cat. A arrives home with cat. A learns about uncle. A and B kiss. A and B get married. A sneezes. '], 
	['inheritance', 'robbery', 'stagecoach', 'anchorhead', 'A gets partial inheritance. A goes to bar. B collects money. A shows B skull. B tells A to go to the White House. A departs with B. A gets amulet. A gets in car. A informs B of arrival. A finds magic shop. A opens safe. A opens a puzzle box. A and B arrive at White House. '], 
	['stagecoach', 'catLover', 'robbery', 'inheritance', 'A arrives with Stagecoach. A enters bank. A pulls out gun. A demands money. B presses alarm. Police arrive. A bandages arm. A attends funeral.'], 
	['inheritance', 'fantasy', 'catLover', 'stagecoach', 'A goes to bar. A slays monster. B tells A to go to the White House. B falls in love with A. A rescues B. A arrives with Stagecoach. A and B kiss. A waits. A slips. A hits the ground. B enters Stagecoach. A and B arrive at White House. '], 
	['pharmacy', 'robbery', 'movie', 'tourBus', "A orders drugs. A drives to B's house. B boards bus. A welcomes B. A departs with B. A drives away. "], 
	['catLover', 'movie', 'inheritance', 'stagecoach', 'A begins the day. A meets B. B tells A to go to the White House. A and B kiss. A learns about uncle. A and B sit down. A slips. A hits the ground. A walks to river. A refuses inheritance. '], 
	['stagecoach', 'robbery', 'catLover', 'movie', "A arrives home with cat. A drives to B's house. B enters Stagecoach. A meets B. A drives to theater. A parks car. A buys tickets. Police arrest A."], 
	['anchorhead', 'robbery', 'tourBus', 'stagecoach', 'A leaves house. B greets A. B tells A to go to the White House. B presses alarm. A arrives with Stagecoach. A finds secret observatory. A waits. A meets B. A arrives at Boarding Location. B gives A money. A and B arrive at White House. '], 
	['fantasy', 'catLover', 'pharmacy', 'movie', 'A parks car. B delivers drugs. A meets B. A uses the bathroom. B falls in love with A. A pays cash. A rescues B. Cat injures A. A leaves.'], 
	['fantasy', 'inheritance', 'catLover', 'movie', "Monster holds B captive. A parks car. A slips. A drives to B's house. A uses the bathroom. A arrives home with cat. A meets B. A rescues B. A refuses inheritance. "], 
	['inheritance', 'movie', 'stagecoach', 'robbery', "A attends funeral. A enters bank. A covers face. A approaches B. A scans bank. A pulls out gun. A converses with B. A demands money. B collects money. B presses alarm. A drives to B's house. B is scared. Police arrive. Police arrest A. "], 
	['pharmacy', 'catLover', 'fantasy', 'anchorhead', 'A shows B skull. B falls in love with A. A arrives home with cat. B asks for prescription. B tells A about sewer. A discovers safe. A and B kiss. B checks prescription. A gets amulet. A and B get married. A sees evil god. '], 
	['pharmacy', 'stagecoach', 'tourBus', 'robbery', 'A orders drugs. B collects money. B gives A money. A departs with B. A informs B of arrival. A arrives at Boarding Location. A tells B to board bus. A asks B whats next. A drives away. '], 
	['robbery', 'anchorhead', 'movie', 'inheritance', "A enters bank. A discovers safe. A goes to bar. A buys tickets. A learns about uncle. A drives to B's house. B says goodbye to A. "], 
	['fantasy', 'catLover', 'movie', 'cattleDriver', 'Monster holds B captive. A slays monster. A meets B. A rescues B. A arrives home with cat. A injures arm. A bandages arm. A and B kiss. A and B live happily ever after. '], 
	['fantasy', 'robbery', 'stagecoach', 'anchorhead', 'Monster holds B captive. A covers face. A slays monster. A opens safe. B falls in love with A. A arrives with Stagecoach. A meets B. A departs with B. A converses with B. A and B get married. A demands money. B tells A about sewer. A discovers book in sewer. '], 
	['tourBus', 'robbery', 'movie', 'fantasy', 'A arrives at Boarding Location. A covers face. A tells B to board bus. A approaches B. A pulls out gun. B boards bus. A and B kiss. A asks B whats next. A uses the bathroom. A parks car. B collects money. A drives away. '], 
	['robbery', 'pharmacy', 'fantasy', 'inheritance', 'A attends funeral. A and B kiss. B greets A. A takes receipt. A and B get married. A leaves. '], 
	['robbery', 'stagecoach', 'catLover', 'fantasy', 'A enters bank. A slays monster. A pulls out gun. A departs with B. B falls in love with A. A arrives home with cat. A and B live happily ever after. '], 
	['fantasy', 'stagecoach', 'robbery', 'catLover', 'A informs B of arrival. A puts on gloves. A rescues cat. Cat injures A. A demands money. A slays monster. B presses alarm. B collects money. Police arrive. B gives A money. A arrives home with cat. A sneezes. '], 
	['inheritance', 'movie', 'anchorhead', 'cattleDriver', 'A gets partial inheritance. A uses the bathroom. A finds magic shop. A slips. A returns with cow. '], 
	['stagecoach', 'catLover', 'anchorhead', 'robbery', 'A leaves house. A gets in car. A gets crypt key. A approaches B. B is scared. A learns safe combo. A hits the ground. A puts on gloves. A rescues cat. A discovers safe. A finds secret observatory. Cat injures A. B greets A. A demands money. B presses alarm. A converses with B. B collects money. A gives B flask. A leaves bank. Police arrive. A bandages arm. A talks to B. Police arrest A. '], 
	['cattleDriver', 'pharmacy', 'movie', 'inheritance', 'A begins the day. A pays cash. A parks car. A meets B. A refuses inheritance. '], 
	['robbery', 'cattleDriver', 'pharmacy', 'stagecoach', "A begins the day. A slips. A bandages arm. B tells A to go to the White House. A covers face. B refuses to sell. A departs with B. A informs B of arrival. B delivers drugs. A converses with B. A and B arrive at White House. "], 
	['robbery', 'cattleDriver', 'inheritance', 'anchorhead', 'A learns about uncle. A scans bank. A gets skull. A attends funeral. A learns safe combo. A gets flask. A gets amulet. A gets in car. A goes to bar. A returns with cow. '], 
	['cattleDriver', 'pharmacy', 'tourBus', 'anchorhead', 'A begins the day. A pays cash. A gets skull. A departs with B. A and B visit a Landmark. A asks B whats next. A takes receipt. A leaves. '], 
	['robbery', 'pharmacy', 'catLover', 'anchorhead', 'A enters bank. A discovers safe. A bandages arm. A finds coffin. A gets flask. A leaves. '], 
	['inheritance', 'pharmacy', 'catLover', 'anchorhead', 'A goes to bar. A gets partial inheritance. A orders drugs. B asks for prescription. A produces prescription. A gives B flask. B tells A about sewer. A talks to B. A arrives home with cat. A sees evil god. '], 
	['cattleDriver', 'inheritance', 'tourBus', 'robbery', 'B greets A. A covers face. A approaches B. B is scared. A pulls out gun. A begins the day. A attends funeral. A asks B whats next. A drives away. '], 
	['robbery', 'fantasy', 'inheritance', 'anchorhead', 'A leaves house. A discovers safe. A gets crypt key. A meets B. A learns safe combo. A talks to B. A and B get married. A finds magic shop. A demands money. A goes to bar. A waits in line. A gets amulet. A gives B amulet. B tells A about sewer. B presses alarm. Police arrive. A gets flask. A discovers book in sewer. '], 
	['robbery', 'inheritance', 'pharmacy', 'tourBus', 'A goes to bar. A tells B to board bus. A swipes a card. B boards bus. A departs with B. A drives away. '], 
	['stagecoach', 'tourBus', 'cattleDriver', 'pharmacy', 'A arrives with Stagecoach. A welcomes B. A orders drugs. B asks for prescription. A smacks saddle. A leaves. '], 
	['inheritance', 'fantasy', 'robbery', 'tourBus', 'A asks B whats next. A approaches B. B is scared. A learns about uncle. A and B kiss. A attends funeral. A pulls out gun. A meets B. B greets A. A refuses inheritance. '], 
	['fantasy', 'inheritance', 'stagecoach', 'robbery', 'B tells A to go to the White House. A approaches B. B greets A. Monster holds B captive. B is scared. A gets partial inheritance. A learns about uncle. A rescues B. A attends funeral. A and B kiss. A covers face. B falls in love with A. '], 
	['stagecoach', 'cattleDriver', 'fantasy', 'inheritance', 'A arrives with Stagecoach. A learns about uncle. A rescues B. A hits the ground. A gets partial inheritance. A collects inheritance. '], 
	['stagecoach', 'fantasy', 'cattleDriver', 'movie', "A parks car. A hits the ground. A meets B. A drives to theater. B tells A to go to the White House. A injures arm. A drives to B's house. A bandages arm. A converses with B. A and B live happily ever after. "], 
	['movie', 'pharmacy', 'fantasy', 'catLover', "A drives to B's house. A arrives home with cat. B falls in love with A. A leaves. "], 
	['tourBus', 'robbery', 'stagecoach', 'anchorhead', 'A shows B skull. B greets A. A tells B to board bus. B boards bus. A arrives with Stagecoach. A meets B. A gives B flask. A opens safe. A gives B amulet. A drives away. '], 
	['tourBus', 'inheritance', 'pharmacy', 'catLover', 'A sees frightened cat at river. A puts on gloves. A rescues cat. A produces prescription. A bandages arm. A tells B to board bus. B checks prescription. A arrives home with cat. Cat injures A. B boards bus. B delivers drugs. A welcomes B. A attends funeral. A sneezes. '], 
	['stagecoach', 'robbery', 'tourBus', 'movie', 'A asks B whats next. A approaches B. B is scared. A arrives at Boarding Location. A tells B to board bus. A and B visit a Landmark. A uses the bathroom. A buys tickets. A and B buy popcorn and soda. A and B walk to car. A and B sit down. A gets in car. B says goodbye to A. '], 
	['anchorhead', 'pharmacy', 'cattleDriver', 'movie', 'A leaves house. A drives to theater. A rescues cow. A meets B. A leaves. '], 
	['cattleDriver', 'fantasy', 'robbery', 'catLover', 'A and B get married. A rides horse. A injures arm. B greets A. A covers face. A approaches B. A pulls out gun. A demands money. B presses alarm. B collects money. A rescues cat. Cat injures A. Police arrive. B is scared. B gives A money. Police arrest A. '], 
	['inheritance', 'robbery', 'cattleDriver', 'movie', 'A gets partial inheritance. A covers face. A uses the bathroom. A drives to theater. A injures arm. A drives away. '], 
	['inheritance', 'catLover', 'robbery', 'fantasy', 'A gets partial inheritance. A covers face. A gets in car. Monster holds B captive. A meets B. A sneezes. '], 
	['fantasy', 'inheritance', 'movie', 'tourBus', "Monster holds B captive. A asks B whats next. A slays monster. A drives to B's house. A attends funeral. A collects inheritance. "], 
	['anchorhead', 'catLover', 'fantasy', 'stagecoach', 'A leaves house. A injures arm. A and B kiss. A waits. B tells A to go to the White House. A and B arrive at White House. '], 
	['stagecoach', 'cattleDriver', 'robbery', 'catLover', 'A arrives with Stagecoach. A covers face. A approaches B. B enters Stagecoach. B tells A to go to the White House. A slips. A sees B. A gets in car. A bandages arm. A drives away. '], 
	['fantasy', 'robbery', 'catLover', 'cattleDriver', 'Monster holds B captive. A approaches B. A rescues cat. A covers face. A injures arm. A pulls out gun. Cat injures A. B is scared. A demands money. B collects money. B presses alarm. A arrives at river. A finds a frightened cow. Police arrive. Police arrest A. '], 
	['catLover', 'robbery', 'anchorhead', 'cattleDriver', 'A leaves house. A finds magic shop. B greets A. A rescues cow. A gets amulet. A learns safe combo. A feeds cats. A gets flask. A hits the ground. A slips. A begins the day. A gives B flask. A sees evil god. '], 
	['anchorhead', 'robbery', 'pharmacy', 'inheritance', 'A leaves house. B refuses to sell. A approaches B. A covers face. A pulls out gun. A leaves bank. Police arrive. A goes to bar. B is scared. A leaves. '], 
	['inheritance', 'anchorhead', 'cattleDriver', 'stagecoach', 'A converses with B. A arrives at river. B tells A to go to the White House. A learns about uncle. A gets partial inheritance. A sees evil god. '], 
	['robbery', 'movie', 'cattleDriver', 'anchorhead', 'A approaches B. A gets skull. A gives B flask. B is scared. B greets A. A talks to B. A finds magic shop. A rides horse. A finds a frightened cow. A hits the ground. A gets amulet. A finds secret observatory. A slips. B tells A about sewer. A arrives at river. A scans bank. B says goodbye to A. '], 
	['anchorhead', 'tourBus', 'robbery', 'movie', 'A leaves house. A arrives at Boarding Location. A approaches B. B gives A money. A and B hold hands. A covers face. A pulls out gun. A demands money. B collects money. A and B buy popcorn and soda. A and B talk. A gets flask. A tells B to board bus. B is scared. B boards bus. A sees B. A gets in car. B says goodbye to A. '], 
	['anchorhead', 'fantasy', 'cattleDriver', 'catLover', 'A leaves house. A injures arm. A slips. A rescues cat. A feeds cats. A walks to river. A and B kiss. A returns with cow. '], 
	['inheritance', 'cattleDriver', 'anchorhead', 'stagecoach', 'A gets flask. A goes to bar. A rescues cow. A converses with B. A and B arrive at White House. '], 
	['inheritance', 'pharmacy', 'catLover', 'anchorhead', 'A finds coffin. A gets skull. A sees frightened cat at river. A puts on gloves. A rescues cat. A goes to bar. Cat injures A. A leaves. '], 
	['fantasy', 'inheritance', 'pharmacy', 'catLover', 'Monster holds B captive. A begins the day. A meets B. B checks prescription. A leaves. '], 
	['inheritance', 'tourBus', 'robbery', 'fantasy', 'A gets partial inheritance. A arrives at Boarding Location. B greets A. A attends funeral. A tells B to board bus. A covers face. A approaches B. A pulls out gun. A and B live happily ever after. '], 
	['fantasy', 'robbery', 'movie', 'tourBus', 'A meets B. A covers face. A drives to theater. A scans bank. A rescues B. A departs with B. A and B visit a Landmark. A and B arrive at Boarding Location. '], 
	['inheritance', 'movie', 'anchorhead', 'stagecoach', "A gets partial inheritance. A drives to B's house. A shows B skull. B tells A to go to the White House. A meets B. A attends funeral. A discovers safe. A collects inheritance. "], 
	['anchorhead', 'robbery', 'fantasy', 'inheritance', 'A leaves house. B greets A. A approaches B. A slays monster. A gets partial inheritance. A covers face. A refuses inheritance. ']]
	return fourStories

def GetQuestions():
	return GetTwoStoryCombos()+GetThreeStoryCombos()+GetFourStoryCombos()

def GetQuestion(index):
	return GetQuestion()[index]